export default [
	{ kana: "あ", romanji: "a" },
	{ kana: "い", romanji: "i" },
	{ kana: "う", romanji: "u" },
	{ kana: "え", romanji: "e" },
	{ kana: "お", romanji: "o" },

	{ kana: "か", romanji: "ka" },
	{ kana: "き", romanji: "ki" },
	{ kana: "く", romanji: "ku" },
	{ kana: "け", romanji: "ke" },
	{ kana: "こ", romanji: "ko" },

	{ kana: "さ", romanji: "sa" },
	{ kana: "し", romanji: "shi" },
	{ kana: "す", romanji: "su" },
	{ kana: "せ", romanji: "se" },
	{ kana: "そ", romanji: "so" },

	{ kana: "た", romanji: "ta" },
	{ kana: "ち", romanji: "chi" },
	{ kana: "つ", romanji: "tsu" },
	{ kana: "て", romanji: "te" },
	{ kana: "と", romanji: "to" },

	{ kana: "な", romanji: "na" },
	{ kana: "に", romanji: "ni" },
	{ kana: "ぬ", romanji: "nu" },
	{ kana: "ね", romanji: "ne" },
	{ kana: "の", romanji: "no" },

	{ kana: "は", romanji: "ha" },
	{ kana: "ひ", romanji: "hi" },
	{ kana: "ふ", romanji: "hu" },
	{ kana: "へ", romanji: "he" },
	{ kana: "ほ", romanji: "ho" },

	{ kana: "ま", romanji: "ma" },
	{ kana: "み", romanji: "mi" },
	{ kana: "む", romanji: "mu" },
	{ kana: "め", romanji: "me" },
	{ kana: "も", romanji: "mo" },

	{ kana: "や", romanji: "ya" },
	{ kana: "ゆ", romanji: "yu" },
	{ kana: "よ", romanji: "yo" },
	
	{ kana: "ら", romanji: "ra" },
	{ kana: "り", romanji: "ri" },
	{ kana: "る", romanji: "ru" },
	{ kana: "れ", romanji: "re" },
	{ kana: "ろ", romanji: "ro" },

	{ kana: "わ", romanji: "wa" },
	{ kana: "を", romanji: "wo" },
	{ kana: "ん", romanji: "n" },

	{ kana: "が", romanji: "ga" },
	{ kana: "ぎ", romanji: "gi" },
	{ kana: "ぐ", romanji: "gu" },
	{ kana: "げ", romanji: "ge" },
	{ kana: "ご", romanji: "go" },

	{ kana: "ざ", romanji: "za" },
	{ kana: "じ", romanji: "ji" },
	{ kana: "ず", romanji: "zu" },
	{ kana: "ぜ", romanji: "ze" },
	{ kana: "ぞ", romanji: "zo" },

	{ kana: "だ", romanji: "da" },
	{ kana: "ぢ", romanji: "di" },
	{ kana: "づ", romanji: "du" },
	{ kana: "で", romanji: "de" },
	{ kana: "ど", romanji: "do" },

	{ kana: "ば", romanji: "ba" },
	{ kana: "び", romanji: "bi" },
	{ kana: "ぶ", romanji: "bu" },
	{ kana: "べ", romanji: "be" },
	{ kana: "ぼ", romanji: "bo" },
	
	{ kana: "ぱ", romanji: "pa" },
	{ kana: "ぴ", romanji: "pi" },
	{ kana: "ぷ", romanji: "pu" },
	{ kana: "ぺ", romanji: "pe" },
	{ kana: "ぽ", romanji: "po" },
];